-- File Upload Project - PostgreSQL Schema
-- PostgreSQL 18.x


CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at_ms()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_now TIMESTAMPTZ(3);
BEGIN
    v_now := date_trunc('milliseconds', clock_timestamp());

    IF OLD.updated_at IS NOT NULL AND v_now <= OLD.updated_at THEN
        NEW.updated_at := OLD.updated_at + INTERVAL '1 millisecond';
    ELSE
        NEW.updated_at := v_now;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT date_trunc('milliseconds', clock_timestamp()),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT date_trunc('milliseconds', clock_timestamp()),

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN'))
);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_ms();

CREATE TABLE IF NOT EXISTS file_extension_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extension       VARCHAR(20) NOT NULL,
    policy_kind     VARCHAR(10) NOT NULL,
    blocked         BOOLEAN NOT NULL,
    created_by      BIGINT NULL,
    updated_by      BIGINT NULL,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT date_trunc('milliseconds', clock_timestamp()),
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT date_trunc('milliseconds', clock_timestamp()),

    CONSTRAINT uk_file_extension_policy_extension UNIQUE (extension),
    CONSTRAINT ck_file_extension_policy_extension
        CHECK (extension ~ '^[a-z0-9]{1,20}$'),
    CONSTRAINT ck_file_extension_policy_kind
        CHECK (policy_kind IN ('FIXED', 'CUSTOM')),
    CONSTRAINT ck_file_extension_policy_custom_blocked
        CHECK (policy_kind = 'FIXED' OR blocked = TRUE),
    CONSTRAINT ck_file_extension_policy_fixed_names
        CHECK (
            policy_kind = 'CUSTOM'
            OR extension IN ('bat','cmd','com','cpl','exe','scr','js')
        ),
    CONSTRAINT fk_file_extension_policy_created_by
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_file_extension_policy_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS trg_file_extension_policy_updated_at ON file_extension_policy;
CREATE TRIGGER trg_file_extension_policy_updated_at
BEFORE UPDATE ON file_extension_policy
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_ms();

CREATE OR REPLACE FUNCTION enforce_custom_extension_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_count INTEGER;
BEGIN
    IF NEW.policy_kind = 'CUSTOM' THEN
        PERFORM pg_advisory_xact_lock(2026082201);

        SELECT COUNT(*)
          INTO v_count
          FROM file_extension_policy
         WHERE policy_kind = 'CUSTOM';

        IF v_count >= 200 THEN
            RAISE EXCEPTION 'custom extension limit exceeded (max=200)'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_custom_extension_limit ON file_extension_policy;
CREATE TRIGGER trg_custom_extension_limit
BEFORE INSERT ON file_extension_policy
FOR EACH ROW
EXECUTE FUNCTION enforce_custom_extension_limit();

CREATE TABLE IF NOT EXISTS policy_audit_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id       BIGINT NOT NULL,
    policy_id           BIGINT NULL,
    extension_snapshot  VARCHAR(20) NOT NULL,
    action              VARCHAR(30) NOT NULL,
    before_blocked      BOOLEAN NULL,
    after_blocked       BOOLEAN NULL,
    reason              VARCHAR(200) NULL,
    created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT date_trunc('milliseconds', clock_timestamp()),

    CONSTRAINT ck_policy_audit_extension
        CHECK (extension_snapshot ~ '^[a-z0-9]{1,20}$'),
    CONSTRAINT ck_policy_audit_action
        CHECK (action IN (
            'FIXED_BLOCK',
            'FIXED_UNBLOCK',
            'CUSTOM_ADD',
            'CUSTOM_DELETE'
        )),
    CONSTRAINT ck_policy_audit_custom_add_reason
        CHECK (
            action <> 'CUSTOM_ADD'
            OR (reason IS NOT NULL AND btrim(reason) <> '')
        ),
    CONSTRAINT fk_policy_audit_actor
        FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_policy_audit_policy
        FOREIGN KEY (policy_id) REFERENCES file_extension_policy(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS files (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    original_filename   VARCHAR(255) NOT NULL,
    storage_key         VARCHAR(512) NOT NULL,
    extension           VARCHAR(20) NOT NULL,
    client_mime_type    VARCHAR(150) NULL,
    detected_mime_type  VARCHAR(150) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    sha256              CHAR(64) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    failure_code        VARCHAR(50) NULL,
    uploaded_by         BIGINT NOT NULL,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT date_trunc('milliseconds', clock_timestamp()),
    updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT date_trunc('milliseconds', clock_timestamp()),

    CONSTRAINT uk_files_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_files_original_filename_not_blank CHECK (btrim(original_filename) <> ''),
    CONSTRAINT ck_files_extension CHECK (extension ~ '^[a-z0-9]{1,20}$'),
    CONSTRAINT ck_files_size CHECK (
        size_bytes > 0
        AND size_bytes < (100::BIGINT * 1024 * 1024)
    ),
    CONSTRAINT ck_files_sha256 CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_files_status CHECK (status IN ('PENDING','COMPLETED','FAILED')),
    CONSTRAINT ck_files_failure_code CHECK (
        (status = 'FAILED' AND failure_code IS NOT NULL)
        OR
        (status IN ('PENDING','COMPLETED') AND failure_code IS NULL)
    ),
    CONSTRAINT fk_files_uploaded_by
        FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE RESTRICT
);

DROP TRIGGER IF EXISTS trg_files_updated_at ON files;
CREATE TRIGGER trg_files_updated_at
BEFORE UPDATE ON files
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_ms();

COMMENT ON TABLE users IS 'Administrator accounts used by Spring Security.';
COMMENT ON TABLE file_extension_policy IS 'Fixed/custom upload block policies.';
COMMENT ON TABLE policy_audit_log IS 'Immutable audit history for policy changes.';
COMMENT ON TABLE files IS 'File metadata. Binary objects are stored in Cloudflare R2.';

COMMENT ON COLUMN users.password_hash IS 'BCrypt encoded password.';
COMMENT ON COLUMN file_extension_policy.extension IS 'Normalized lowercase extension without leading dot.';
COMMENT ON COLUMN files.original_filename IS 'Original display filename. Application permits Korean filename characters.';
COMMENT ON COLUMN files.storage_key IS 'Server-generated private R2 object key.';
COMMENT ON COLUMN files.client_mime_type IS 'Untrusted client supplied MIME.';
COMMENT ON COLUMN files.detected_mime_type IS 'Server detected MIME.';
COMMENT ON COLUMN files.metadata IS 'Future JSONB metadata slot; no GIN index initially.';

